name: The Ranting Rabbit
markdown: redcarpet
highlighter: pygments
description: "A place to kick it and chill...oh and rant"
permalink: /posts/:title
exclude:   [node_modules,'Gruntfile.js', 'package.json']
