---
title: The Bunnz Chronicle
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
kramdown:
  input: GFM
description: A place to kick it and chill...oh and rant
permalink: pretty
exclude:
- node_modules
- Gruntfile.js
- package.json
excerpt_separator: "<!--more-->"
owner:
  name: Rodrigo Ibarra
  avatar: me.jpg
  bio: Soy Rodrigo Ibarra, la mayor parte de la gente me conoce como bony y soy diseñador
    grafico, geek, idiota profesional.
  email: hola@rodrigo-ibarra.com
  twitter: _rodrigoibarra
  facebook: https://www.facebook.com/killabunzz
  github: https://github.com/rodrigoibarra/rodrigo-ibarra-site
  instagram: http://instagram.com/killerbunnz
